# Generated by Django 5.1.6 on 2025-03-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='current_prize',
            field=models.FloatField(default=123),
            preserve_default=False,
        ),
    ]
