# Generated by Django 5.1.6 on 2025-03-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_listing_current_prize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='current_prize',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
