# Generated by Django 5.1.6 on 2025-03-05 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_listing_current_highest_bidder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='current_highest_bidder',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='current_prize',
        ),
        migrations.AddField(
            model_name='bid',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_bids', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
