# Generated by Django 5.1.6 on 2025-03-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_remove_listing_current_highest_bidder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='current_prize',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
