# Generated by Django 5.1.6 on 2025-03-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_alter_bid_if_last_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='if_last_bid',
            field=models.BooleanField(default=True),
        ),
    ]
