# Generated by Django 5.1.6 on 2025-03-07 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_listing_auction_winner_alter_listing_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='written_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
